sms_home:
    path:      /{page}
    defaults:
        _controller: StatsBundle:Default:index
        page:        1
    requirements:
        page: \d*

sms_view:
    path:      /user/{id}
    defaults:
        _controller: StatsBundle:Default:viewUser
    requirements:
        id: \d+
