sms:
    resource: "@StatsBundle/Resources/config/routing.yml"

sms_admin:
    resource: "@StatsBundle/Resources/config/routing_admin.yml"
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
